ACMG_criteria = {
    "PVS1_Very Strong" : "Varijanta dovodi do uvođenja prevremenog stop kodona, te kao takva predstavlja „nultu“ varijantu u genu za koji je gubitak funkcije poznati mehanizam nastanka bolesti (PVS1_Very Strong).",
    "PS1_Strong" : "Prijavljena je alternativna patogena varijanta ___ koja dovodi do iste aminokiselinske promene (PS1_Strong).",
    "PS2_Strong" : "Varijanta je kod pacijenta nastala de novo i nije prisutna kod roditelja, uz potvrđeno biološko srodstvo i odsustvo kliničkih simptoma kod oba roditelja (PS2_Strong).",
    "PS3_Very Strong" : "Varijanta je u ClinVar, UniProt i LOVD bazama podataka kao i u literaturi opisana kao patogena [citat] (PS3_Very Strong).",
    "PS3_Strong" : "Varijanta je u ClinVar, UniProt i LOVD bazama podataka kao i u literaturi opisana kao patogena [citat] (PS3_Strong).",
    "PS3_Moderate" : "Varijanta je u ClinVar, UniProt i LOVD bazama podataka kao i u literaturi opisana kao patogena [citat] (PS3_Moderate).",
    "PS3_Supporting" : "Varijanta je u ClinVar, UniProt i LOVD bazama podataka kao i u literaturi opisana kao patogena [citat]",
    "PS4_Moderate" : "Varijanta je detektovana kod nekoliko pacijenata u srodstvu koji imaju kliničku dijagnozu (PS4_Moderate).",
    "PM1_Very Strong" : "Varijanta se nalazi u „hot-spot“ regionu proteina.",
    "PM1_Strong" : "Varijanta se nalazi u „hot-spot“ regionu proteina.",
    "PM1_Moderate" : "Varijanta se nalazi u „hot-spot“ regionu proteina.",
    "PM1_Supporting" : "Varijanta se nalazi u „hot-spot“ regionu proteina.",
    "PM2_Moderate" : "Varijanta je nađena sa niskom učestalošću u GnomAD Exomes i GnomAD Genomes populacionim bazama podataka (PM2_Moderate).",
    "PM2_Supporting" : "Varijanta je nađena sa niskom učestalošću u GnomAD Exomes i GnomAD Genomes populacionim bazama podataka (PM2_Moderate).",
    "PM3_Very Strong" : "Za recesivna oboljenja, varijanta je detektovana u homozigotnom stanju. (PM3_Very Strong).",
    "PM3_Strong" : "Za recesivna oboljenja, varijanta je detektovana u homozigotnom stanju. (PM3_Very Strong).",
    "PM3_Moderate" : "Za recesivna oboljenja, varijanta je detektovana u homozigotnom stanju. (PM3_Very Strong).",
    "PM3_Supporting" : "Za recesivna oboljenja, varijanta je detektovana u homozigotnom stanju. (PM3_Very Strong).",
    "PM4_Very_Strong" : "Varijanta dovodi do gubitka stop kodona i kao takva utiče na dužinu transkripta i posledično na strukturu i/ili funkciju proteina (PM4_Strong).",
    "PM4_Strong" : "Varijanta dovodi do gubitka stop kodona i kao takva utiče na dužinu transkripta i posledično na strukturu i/ili funkciju proteina (PM4_Strong).",
    "PM4_Moderate" : "Varijanta dovodi do gubitka stop kodona i kao takva utiče na dužinu transkripta i posledično na strukturu i/ili funkciju proteina (PM4_Strong).",
    "PM4_Supporting" : "Varijanta dovodi do gubitka stop kodona i kao takva utiče na dužinu transkripta i posledično na strukturu i/ili funkciju proteina (PM4_Strong).",
    "PM5_Very Strong" : "Varijanta se nalazi u kodonu u kojem je prethodno prijavljena patogena varijanta (PM5_Moderate).",
    "PM5_Strong" : "Varijanta se nalazi u kodonu u kojem je prethodno prijavljena patogena varijanta (PM5_Moderate).",
    "PM5_Moderate" : "Varijanta se nalazi u kodonu u kojem je prethodno prijavljena patogena varijanta (PM5_Moderate).",
    "PM5_Supporting" : "Varijanta se nalazi u kodonu u kojem je prethodno prijavljena patogena varijanta (PM5_Moderate).",
    "PP1_Supporting" : "Uočeni fenotip kod pacijenta je u literaturi i bazama podataka asociran sa genom ___ (PP1_Moderate)."
}