ACMG_criteria = {
    "PVS1_Very Strong" : "Varijanta dovodi do uvođenja prevremenog stop kodona, te kao takva predstavlja „nultu“ varijantu u genu za koji je gubitak funkcije poznati mehanizam nastanka bolesti (PVS1_Very Strong).",
    "PS1_Strong" : "Prijavljena je alternativna patogena varijanta ___ koja dovodi do iste aminokiselinske promene (PS1_Strong).",
    "PS2_Strong" : "Varijanta je kod pacijenta nastala de novo i nije prisutna kod roditelja, uz potvrđeno biološko srodstvo i odsustvo kliničkih simptoma kod oba roditelja (PS2_Strong).",
    "PS3_Very Strong" : "Varijanta je u ClinVar, UniProt i LOVD bazama podataka kao i u literaturi opisana kao patogena [broj citata] (PS3_Very Strong).",
    "PS3_Strong" : "Varijanta je u ClinVar, UniProt i LOVD bazama podataka kao i u literaturi opisana kao patogena [broj citata] (PS3_Strong).",
    "PS3_Moderate" : "Varijanta je u ClinVar, UniProt i LOVD bazama podataka kao i u literaturi opisana kao patogena [broj citata] (PS3_Moderate).",
    "PS3_Supporting" : "Varijanta je u ClinVar, UniProt i LOVD bazama podataka kao i u literaturi opisana kao patogena [broj citata] (PS3_Supporting).",
    "PS4_Moderate" : "Varijanta je detektovana kod nekoliko pacijenata u srodstvu koji imaju kliničku dijagnozu (PS4_Moderate).",
    "PM1_Very Strong" : "Varijanta se nalazi u „hot-spot“ regionu proteina (PM1_Very Strong).",
    "PM1_Strong" : "Varijanta se nalazi u „hot-spot“ regionu proteina (PM1_Strong).",
    "PM1_Moderate" : "Varijanta se nalazi u „hot-spot“ regionu proteina (PM1_Modereate).",
    "PM1_Supporting" : "Varijanta se nalazi u „hot-spot“ regionu proteina (PM1_Supporting).",
    "PM2_Moderate" : "Varijanta je nađena sa niskom učestalošću u GnomAD Exomes i GnomAD Genomes populacionim bazama podataka (PM2_Moderate).",
    "PM2_Supporting" : "Varijanta je nađena sa niskom učestalošću u GnomAD Exomes i GnomAD Genomes populacionim bazama podataka (PM2_Supporting).",
    "PM3_Very Strong" : "Za recesivna oboljenja, varijanta je detektovana u homozigotnom stanju. (PM3_Very Strong).",
    "PM3_Strong" : "Za recesivna oboljenja, varijanta je detektovana u homozigotnom stanju. (PM3_Strong).",
    "PM3_Moderate" : "Za recesivna oboljenja, varijanta je detektovana u homozigotnom stanju. (PM3_Moderate).",
    "PM3_Supporting" : "Za recesivna oboljenja, varijanta je detektovana u homozigotnom stanju. (PM3_Supporting).",
    "PM4_Very_Strong" : "Varijanta dovodi do gubitka stop kodona i kao takva utiče na dužinu transkripta i posledično na strukturu i/ili funkciju proteina (PM4_Very Strong).",
    "PM4_Strong" : "Varijanta dovodi do gubitka stop kodona i kao takva utiče na dužinu transkripta i posledično na strukturu i/ili funkciju proteina (PM4_Strong).",
    "PM4_Moderate" : "Varijanta dovodi do gubitka stop kodona i kao takva utiče na dužinu transkripta i posledično na strukturu i/ili funkciju proteina (PM4_Modereate).",
    "PM4_Supporting" : "Varijanta dovodi do gubitka stop kodona i kao takva utiče na dužinu transkripta i posledično na strukturu i/ili funkciju proteina (PM4_Supporting).",
    "PM5_Very Strong" : "Varijanta se nalazi u kodonu u kojem je prethodno prijavljena patogena varijanta (PM5_Very Strong).",
    "PM5_Strong" : "Varijanta se nalazi u kodonu u kojem je prethodno prijavljena patogena varijanta (PM5_Strong).",
    "PM5_Moderate" : "Varijanta se nalazi u kodonu u kojem je prethodno prijavljena patogena varijanta (PM5_Moderate).",
    "PM5_Supporting" : "Varijanta se nalazi u kodonu u kojem je prethodno prijavljena patogena varijanta (PM5_Supporting).",
    "PP1_Moderate" : "Uočeni fenotip kod pacijenta je u literaturi i bazama podataka asociran sa genom ___ (PP1_Moderate).",
    "PP1_Supporting" : "Uočeni fenotip kod pacijenta je u literaturi i bazama podataka asociran sa genom ___ (PP1_Supporting).",
    "PP2_Moderate" : "Varijanta se nalazi u genu u kome su missense varijante čest uzrok nastanka bolesti (PP2_Moderate).",
    "PP2_Supporting" : "Varijanta se nalazi u genu u kome su missense varijante čest uzrok nastanka bolesti (PP2_Supporting).",
    "PP3_Very Strong" : "Za ovu varijantu postoje dokazi iz kompjuterskih predikcija koji idu u prilog njenoj patogenosti i koji ukazuju da ova varijanta ima uticaj na iskrajanje transkripta i funkcionalnost proteinskog produkta (PP3_Very Strong).",
    "PP3_Strong" : "Za ovu varijantu postoje jaki dokazi iz kompjuterskih predikcija koji idu u prilog njenoj patogenosti (PP3_Strong).",
    "PP3_Moderate" : "Za ovu varijantu postoje dokazi iz kompjuterskih predikcija koji idu u prilog njenoj patogenosti (PP3_Moderate).",
    "PP3_Supporting" : "Za ovu varijantu postoje dokazi iz kompjuterskih predikcija koji idu u prilog njenoj patogenosti (PP3_Supporting).",
    "PP4_Supporiting" : "Fenotip pacijenta je retka kombinacija kliničkih karakteristika za koje postoji ograničen broj genetičkih etiologija (PP4_Supporiting).",
    "PP5_Very Strong" : "Varijanta je prethodno prijavljena kao patogena (PP5_Very Strong). [broj citata]",
    "PP5_Strong" : "Varijanta je prethodno prijavljena kao patogena (PP5_Strong). [broj citata]",
    "PP5_Moderate" : "Varijanta je prethodno prijavljena kao patogena (PP5_Very Strong). [broj citata]",
    "PP5_Supporting" : "Varijanta je prethodno prijavljena kao patogena (PP5_Supporting). [broj citata]",
    "BP1_Supporting" : "Varijanta se nalazi u genu u kome missense varijante nisu čest uzrok nastanka bolesti (BP1_Supporting).",
    "BP3_Supporting" : "Missense varijanta se nalazi u regionu niske konzerviranosti (BP3_Supporting).",
    "BP4_Supporting" : "Za ovu varijantu postoje dokazi iz kompjuterskih predikcija koji idu u prilog njenoj benignosti (BP4_Supporting).",
    "BP4_Modereate" : "Za ovu varijantu postoje dokazi iz kompjuterskih predikcija koji idu u prilog njenoj benignosti (BP4_Moderate).",
    "BS1_Strong" : "Varijanta je nađena sa relativno visokom učestalošću u GnomAD Exomes i GnomAD Genomes populacionim bazama podataka (BS1_Strong).",
    "BS2_Strong" : "Varijanta je detektovana kod zdravih odraslih osoba (BS2_Strong).",
    "BA1_Stand Alone" : "Varijanta je nađena sa visokom učestalošću u GnomAD Exomes i GnomAD Genomes populacionim bazama podataka (BA1_Stand Alone)."
}